---
# tasks file for roles/mongodb
- name: Install mongodb-server
  become: yes
  package:
    name: mongodb-server
    state: installed

- name: Install mongodb
  become: yes
  package:
    name: mongodb
    state: installed 

- name: Extracting mongodb_ACIT4640.tgz
  become: yes
  become_user: todoapp
  get_url:
    url: https://acit4640.y.vu/docs/module06/resources/mongodb_ACIT4640.tgz
    dest: /home/todoapp
    url_username: BCIT
    url_password: w1nt3r2020

- name: Unpack mongodb
  become: yes
  become_user: todoapp
  unarchive:
    src: /home/todoapp/mongodb_ACIT4640.tgz
    dest: /home/todoapp
    remote_src: yes
  
- name: Enabling and starting the mongod
  become: yes
  systemd:
    name: mongod
    state: started
    enabled: yes

- name: Importing the data to the database
  become: yes
  command: mongorestore -d acit4640 ACIT4640/
  args: 
    chdir: /home/todoapp

- name: copying the database file
  become: yes
  template:
    src: database.js.j2
    dest: /home/todoapp/app/ACIT4640-todo-app/config/database.js

