---
# tasks file for roles/nginx
- name: Install nginx
  become: yes
  package:
    name: nginx
    state: installed

- name: copying the nginx file
  become: yes
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: starting the nginx service
  become: yes
  systemd:
    name: nginx
    state: started



