--- 
- name: Creating new user todoapp
  become: true
  user:
    name: todoapp
    password: "{{ 'P@ssw0rd' | password_hash('sha512') }}"

- name: Setenforce disabled
  become: yes
  selinux: 
    state: disabled

- name: Firewall settings 
  become: true
  shell: firewall-cmd --zone=public --add-port=8080/tcp