---
# tasks file for roles/todoapp_service

- name: Creating the app directory 
  become: true
  file:
    path: /home/todoapp/app
    state: directory
    mode: "0755"

- name: Changing the ownership
  become: "yes"
  file:
    path: /home/todoapp
    mode: "0755"
    owner: todoapp
    group: todoapp

- name: copying the todoapp file
  become: yes
  template:
    src: todoapp.service.j2
    dest: /etc/systemd/system/todoapp.service

- name: enabling and starting todoapp.service, daemon-reload
  become: yes
  systemd:
    name: todoapp.service
    state: started
    enabled: yes
    daemon_reload: yes