Vagrant.configure("2") do |config|

  #Base box specification
  config.vm.box = "basebox_4640"

  #User and SSH specifications
  config.ssh.username = "admin"
  config.ssh.private_key_path = "./files/acit_admin_id_rsa"

  #Configuring the VM
  config.vm.define "todoapp" do |todoapp|
    todoapp.vm.hostname = "todoapp.bcit.local"
    todoapp.vm.network "forwarded_port", guest: 80, host: 12080
      todoapp.vm.synced_folder ".", "/vagrant", disabled: true
    #todoapp.vm.provision "file", source: "./files/nginx.conf", destination: "/home/admin/nginx.conf"
    #todoapp.vm.provision "file", source: "./files/todoapp.service", destination: "/home/admin/todoapp.service"
    #todoapp.vm.provision "file", source: "./files/database.js", destination: "/home/admin/database.js"
    #todoapp.vm.provision "shell" do |shell|
      #shell.path = "./files/install_script.sh" 


   #todoapp.vm.provision "shell", inline: <<-SHELL
     #setenforce 0
     #yum -y install nginx
    #systemctl start nginx
   #SHELL
   
      #Configuring todoapp
      config.vm.provision "ansible" do |ansible|
    ansible.playbook = "todoapp.yaml"
    end

    #Machine specifications
    todoapp.vm.provider "virtualbox" do |vb|
      vb.name = "TODO_4640"
      vb.linked_clone = true
    end
  end

end