Vagrant.configure("2") do |config|
  config.vm.box = "basebox_4640"

  config.ssh.username = "admin"
  config.ssh.private_key_path = "./.ssh/acit_admin_id_rsa"

  config.vm.define "todoapp" do |todoapp|
    todoapp.vm.hostname = "todoapp.bcit.local"
    todoapp.vm.network "forwarded_port", guest: 80, host: 12080
    todoapp.vm.synced_folder ".", "/vagrant", disabled: true
    todoapp.vm.provision "file", source: "./setup", destination: "/home/admin/setup"
    todoapp.vm.provision "file", source: "./.ssh", destination: "/home/admin/.ssh"
    todoapp.vm.provision "shell" do |shell|
      shell.path = "./setup/install_script.sh"

#   todoapp.vm.provision "shell", inline: <<-SHELL
#     setenforce 0
#     yum -y install nginx
#    systemctl start nginx
#   SHELL

    end

    todoapp.vm.provider "virtualbox" do |vb|
      vb.name = "TODO_4640"
      vb.linked_clone = true
    end
  end



end